---

- name: Tekla plugin dev box provision
  hosts: all

  tasks:
    - name: Print host information
      debug:
        msg: "{{ ansible_fqdn }}: {{ ansible_distribution }} {{ ansible_distribution_version}}"

    - name: Install Google Chrome browser
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes

    - name: Install Mozilla Firefox browser
      win_chocolatey:
        name: firefox
        state: present

    - name: Add 'uBlock Origin' extension to Google Chrome
      win_regedit:
        path: HKLM:\SOFTWARE\WOW6432Node\Google\Chrome\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm
        name: update_url
        data: https://clients2.google.com/service/update2/crx

    - name: Install Microsoft Visual C++ redistributables
      win_chocolatey:
        name:
        - vcredist2010
        - vcredist2013
        - vcredist140
        state: present

    - name: Install Tekla Structures
      win_package:
        path: "C:\\tekla_distr\\tekla2020rus\\Tekla Structures 2020\\Tekla Structures 2020.msi"
        state: present
        arguments: /passive /norestart
      register: tekla_installation

    - name: Set Tekla Structures interface language to Russian
      win_regedit:
        path: "HKCU:\\Software\\Trimble\\Tekla Structures\\2020.0\\Settings"
        name: Culture
        data: ru-RU

    - name: Copy custom Tekla Structures settings file
      win_copy:
        src: templates/tekla_custom_settings.ini
        dest: "C:\\Users\\vagrant\\Documents\\tekla_custom_settings.ini"

    - name: Install Git
      win_chocolatey:
        name:
        - git
        state: present

    - name: Make sure Total Commander settings directory exists
      win_file:
        path: "C:\\Users\\vagrant\\AppData\\Roaming\\GHISLER"
        state: directory

    - name: Check if Total Commander settings file exists
      win_stat:
        path: "C:\\Users\\vagrant\\AppData\\Roaming\\GHISLER\\wincmd.ini"
      register: win_cmd_ini

    # Note: we do this BEFORE TC installation on purpose, since the installer
    # creates default version of the config file
    - name: Copy Total Commander settings file
      win_copy:
        src: templates/wincmd.ini
        dest: "C:\\Users\\vagrant\\AppData\\Roaming\\GHISLER\\wincmd.ini"
      when: not win_cmd_ini.stat.exists

    - name: Total Commander
      win_chocolatey:
        name:
        - totalcommander
        state: present
        package_params: /DesktopIcon

    - name: Remove shortcut to 16-bit version of Total Commander
      win_file:
        path: "c:\\Users\\Public\\Desktop\\Total Commander.lnk"
        state: absent

    - name: Install Visual Studio 2019 Community
      win_chocolatey:
        name:
          - visualstudio2019community
        state: present
        # '--locale' changes the display language of the user interface for the installer itself
        # '--addProductLang' determines the UI language packs that are installed to the product
        package_params: --locale en-US --addProductLang en-US --addProductLang ru-RU --passive
      register: vs_installation

    - name: Add VS 2019 shortcut to the desktop
      win_copy:
        src: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Visual Studio 2019.lnk"
        dest: "C:\\Users\\Public\\Desktop\\Visual Studio 2019.lnk"
        remote_src: yes

    - name: Reboot the VM
      win_reboot:
      when: tekla_installation.changed or vs_installation.changed

    - name: Install .NET Desktop Development workload for VS 2019
      win_chocolatey:
        name:
          - visualstudio2019-workload-manageddesktop
        state: present
